spring:
  datasource:
    password: "root"
    username: "root"
#    username: "db_s1"
#    password: "RGfcMGTy2BDDDeHz"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/db_s1"
#    url: "jdbc:mysql://211.101.234.110:3306/db_s1"
mybatis:
  mapper-locations: "classpath:/mapper/*.xml"
---
spring:
  servlet:
    multipart:
      max-file-size: 20MB
